version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/elena/lena/receipt_generation/service_receipt/app_receipt/media/PDF:/usr/src/app/app_receipt/media/PDF
    ports:
      - "8080:8000"
    env_file:
      - .env
    container_name: django_dev
    depends_on:
      - db
  db:
    image: 'postgres:16-alpine'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    restart: always
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=service_receipt
      - POSTGRES_PASSWORD=/run/secrets/db-password
      - POSTGRES_USER=user_db
    healthcheck:
      test: [ "CMD",  "pg_isready -d service_receipt -U user_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/elena/lena/receipt_generation/service_receipt/app_receipt/media/PDF:/usr/src/app/app_receipt/media/PDF
    container_name: celery_worker
    command: celery -A service_receipt worker -l info
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis
    container_name: 'redis-server'
    restart: unless-stopped
    ports:
      - "6378:6379"
volumes:
  postgres_data:
secrets:
  db-password:
    file: app_receipt/db/password.txt